blog/urls.py
from django.urls import path 
from .views import *
from . import views

app_name = 'blog'
urlpatterns = [
    #path('blog', views.blog, name='blog'),
    path("blog/<int:pk>", ArticleDetailView.as_view(), name="article"),
    path("blog", BlogView.as_view(), name="blog"),

    path("dashboard/", views.thedashboard, name="dashboard"),
    path("dashboard/blog/add-new", AddPost.as_view(), name="add-post"),
    path("dashboard/blog/update-post", UpdatePostListView.as_view(), name="update-post-list"),
    path("dashboard/blog/add-category", AddCategory.as_view(), name="add-category"),
    path("dashboard/blog/add-category", views.listcategory, name="add-category"),
    path("dashboard/blog/edit-post/<int:pk>", EditPostView.as_view(), name="edit-post"),
    path("dashboard/blog/<int:pk>/delete", PostDeleteView.as_view(), name="delete-post"),
    path("blog/category/<str:cat>/", CategoryView, name="category"),
    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("resume.urls", namespace='resume')),
    path('superuser/', include('django.contrib.auth.urls')),
    path('superuser/login', include("login.urls")),
    path('', include("blog.urls", namespace='blog')),
    
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path
from . import views
from .views import *



app_name = 'resume'

urlpatterns = [
    path('', views.HomeView, name='home'),
    path('about', views.AboutView, name='about'),
    path('portfolio', views.PortfolioView, name='portfolio'),
    path('contact', views.ContactView, name='contact'),
    #path('dashboard/portfolio/edit/<str:pk>', PortfolioEdit.as_view(), name="portfolio-edit")

]

blog/models.py
from django.db import models
from django.contrib.auth.models import  User
from django.urls import reverse
from ckeditor.fields import RichTextField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:update-post-list")
    


class Post(models.Model):


    STATUS_CHOICES = (                                 
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    snippet = models.CharField(max_length=100, null=True)
    PreviewImage = models.ImageField(upload_to='PostImage')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(null=True, blank=True)
    #body = models.TextField()
    publish = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    status = models.CharField( max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    category = models.CharField(max_length=50, default='uncategorized')

    def __str__(self):
        return self.title + " | " + str(self.author)

    def get_absolute_url(self):
        return reverse("blog:update-post-list")
    

    

blog/forms.py
from django import forms 
from .models import Post, Category

choices = Category.objects.all().values_list('name', 'name')

choice_list = []

for item in choices:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ("title", 'PreviewImage', 'author', 'category', 'status', 'body')

        widgets = {
            'title':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your post title...'}),
            'PreviewImage':forms.FileInput(attrs={'class': 'form-control'}),
            'author':forms.Select(attrs={'class': 'form-control col-sm-4'}),
            'category':forms.Select(choices=choice_list, attrs={'class': 'form-control col-sm-4'}),
            'status':forms.Select(attrs={'class': 'form-control col-sm-4'}),
            'body':forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your post here...' }),
        }


class EditPostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ("title", 'PreviewImage','category', 'status', 'body')

        widgets = {
            'title':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your post title...'}),
            'PreviewImage':forms.FileInput(attrs={'class': 'form-control'}),
            'category':forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'status':forms.Select(attrs={'class': 'form-control'}),
            'body':forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your post here...' }),
        }

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category 
from .forms import PostForm, EditPostForm
from django.urls import reverse_lazy


##################################################BlogViews################################################
#This view will show all the blogs we have published.
class BlogView(ListView): 
    queryset = Post.published.all()
    model = Post
    template_name = "blog/blog.html"
    ordering = ['-publish_date']

#This view will show all our posts within a certain category
def CategoryView(request, cat):
    category_posts = Post.objects.filter(category=cat.replace('-', ' '))

    context= {'cat':cat.title().replace('-', ' '), 'category_posts': category_posts}

    return render(request, 'blog/categories.html', context)

#This will be the article view where we can read a full blog post.
class ArticleDetailView(DetailView):
    model = Post
    template_name = "blog/article_detail.html"

#This is where we will have our portfolio edit 
class PortfolioEdit(CreateView):
    model = Post
    fields = '__all__'
    template_name = "blog/portfolio-edit.html"

class AddPost(CreateView):
    model = Post
    form_class = PostForm
    #fields = '__all__'
    template_name = "blog/add-new.html"

#Add new category to list
class AddCategory(CreateView):
    model = Category
    #form_class = PostForm
    fields = '__all__'
    template_name = "blog/add-category.html"

def listcategory(request):
    cat_list = Category.objects.all()

    context = {'cat_list':cat_list}

    return render(request, "blog/add-category.html", context)


class EditPostView(UpdateView):
    model = Post
    form_class = EditPostForm
    template_name = "blog/edit-post.html"
    #fields = ['title', 'preview_image', 'body']

class UpdatePostListView(ListView):
    model = Post
    template_name = "blog/update-post.html"
    fields = '__all__'


class PostDeleteView(DeleteView):
    model = Post
    template_name = "blog/delete-post.html"
    success_url = reverse_lazy('update-post-list')


# Include Views Test
class PreviewDetailView(DetailView):
    model = Post
    template_name = "blog/preview.html"


def thedashboard(request):
    post_count = Post.objects.all().count()

    context={'post_count':post_count, }
    return render(request, "blog/dashboard.html", context)

blog/templates/blog/401.html
{% extends 'dashboard-base.html' %}

{% load static %}

{% block title %}

401 | Not authorised
{% endblock title %}

{% block content %}

<div id="layoutError">
    <div id="layoutError_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center mt-4">
                            <img class="img-fluid p-4" src="{% static 'assets/img/freepik/401-error-unauthorized-pana.svg' %}" alt />
                            <p class="lead">Access to this resource is denied.</p>
                            <a class="btn btn-primary btn-sm" href="{% url 'home' %}">
                                <i class="ml-0 mr-1" data-feather="home"></i>
                                Home
                            </a>
                            <a class="btn btn-primary btn-sm" href="{% url 'login' %}">
                                <i class="ml-0 mr-1" data-feather="log-in"></i>
                                Login
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutError_footer">
        {% include 'blog/footer.html' %}
    </div>
</div>


{% endblock content %}

blog/templates/blog/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Blog - Bukhosi Moyo</title>  
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="{% static 'css/preloader.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/circle.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fm.revealator.jquery.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- CSS Skin File -->
    <link href="{% static 'css/skins/blue.css' %}" rel="stylesheet">

    

    <!-- Modernizr JS File -->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

    
    </style>
</head>

    <body class="blog">

        {% block content %}

                <header class="header" id="navbar-collapse-toggle">
                    <!-- Fixed Navigation Starts -->
                    <ul class="icon-menu d-none d-lg-block revealator-slideup revealator-once revealator-delay1">
                        <li class="icon-box">
                                <i class="fa fa-home"></i>
                                <a href="{% url 'resume:home' %}">
                                    <h2>Home</h2>
                                </a>
                            </li>
                            <li class="icon-box">
                                <i class="fa fa-user"></i>
                                <a href="{% url 'resume:about' %}">
                                    <h2>About</h2>
                                </a>
                            </li>
                            <li class="icon-box">
                                <i class="fa fa-briefcase"></i>
                                <a href="{% url 'resume:portfolio' %}">
                                    <h2>Portfolio</h2>
                                </a>
                            </li>
                            <li class="icon-box active">
                                <i class="fa fa-comments"></i>
                                <a href="{% url 'blog:blog' %}">
                                    <h2>Blog</h2>
                                </a>
                            </li>
                            <li class="icon-box">
                                <i class="fa fa-envelope-open"></i>
                                <a href="{% url 'resume:contact' %}">
                                    <h2>Contact</h2>
                                </a>
                            </li>
                    </ul>
                    <!-- Fixed Navigation Ends -->
                    <!-- Mobile Menu Starts -->
                    <nav role="navigation" class="d-block d-lg-none">
                        <div id="menuToggle">
                            <input type="checkbox" />
                            <span></span>
                            <span></span>
                            <span></span>
                            <ul class="list-unstyled" id="menu">
                                <li><a href="{% url 'resume:home' %}"><i class="fa fa-home"></i><span>Home</span></a></li>
                                <li><a href="{% url 'resume:about' %}"><i class="fa fa-user"></i><span>About</span></a></li>
                                <li><a href="{% url 'resume:portfolio' %}"><i class="fa fa-folder-open"></i><span>Portfolio</span></a></li>
                                <li class="active"><a href="{% url 'blog:blog' %}"><i class="fa fa-comments"></i><span>Blog</span></a></li>
                                <li><a href="{% url 'resume:contact' %}"><i class="fa fa-envelope-open"></i><span>Contact</span></a></li>
                            </ul>
                        </div>
                    </nav>
                    <!-- Mobile Menu Ends -->
                </header>
                <!-- Header Ends -->
                <!-- Page Title Starts -->
                <section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1">
                    <h1>my <span>blog</span></h1>
                    <span class="title-bg">posts</span>
                </section>
                <!-- Page Title Ends -->
                <!-- Main Content Starts -->
                <section class="main-content revealator-slideup revealator-once revealator-delay1">
                    <div class="container">
                        <!-- Articles Starts -->
                        <div class="row">
                            <!-- Article Starts -->
                            {% for post in object_list %}
                                <div class="col-12 col-md-6 col-lg-6 mb-30 ">
                                    <article class="post-container">
                                        <div class="post-thumb" >
                                            <a href="{% url 'blog:category' post.category %}" class="card-post__category badge badge-pill badge-primary">{{post.category}}</a>
                                            <a href="{% url 'blog:article' post.pk %}" class="d-block position-relative overflow-hidden">
                                                <img src="{{post.PreviewImage.url}}" class="img-fluid" alt="Blog Post" style="width: 100%; height:250px; object-fit: cover ">
                                            </a>
                                        </div>
                                        <div class="post-content ">
                                            <div class="entry-header">
                                                <h3><a href="{% url 'blog:article' post.pk %}">{{post.title}}</a></h3>
                                            </div>
                                            <div class="entry-content open-sans-font ">
                                                <p>{{post.body|slice:':160'|safe}}... <strong> <a href="{% url 'blog:article' post.pk %}">[Readmore]</a> </strong>
                                                </p>
                                            </div>
                                            <hr>

                                            <div>
                                            </div>
                                        </div>
                                    </article>
                                </div>
                            {% endfor %}
                            <!-- Article Ends -->
                            <!-- Article Starts -->
                            
                            <!-- Pagination Starts -->
                            <div class="col-12 mt-4">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center mb-0">
                                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- Pagination Ends -->
                        </div>
                        <!-- Articles Ends -->
                    </div>

                </section>

        {% endblock content %}

        <!-- Template JS Files -->
        <script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
        <script src="{% static 'js/styleswitcher.js' %}"></script>
        <script src="{% static 'js/preloader.min.js' %}"></script>
        <script src="{% static 'js/fm.revealator.jquery.min.js' %}"></script>
        <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
        <script src="{% static 'js/classie.js' %}"></script>
        <script src="{% static 'js/cbpGridGallery.js' %}"></script>
        <script src="{% static 'js/jquery.hoverdir.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>

    </body>
</html>

blog/templates/blog/categories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Blog - Bukhosi Moyo</title>  
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="{% static 'css/preloader.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/circle.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fm.revealator.jquery.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- CSS Skin File -->
    <link href="{% static 'css/skins/blue.css' %}" rel="stylesheet">

    

    <!-- Modernizr JS File -->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

    
    </style>
</head>

    <body class="blog">

        {% block content %}



        <header class="header" id="navbar-collapse-toggle">
    <!-- Fixed Navigation Starts -->
    <ul class="icon-menu d-none d-lg-block revealator-slideup revealator-once revealator-delay1">
        <li class="icon-box">
                <i class="fa fa-home"></i>
                <a href="{% url 'resume:home' %}">
                    <h2>Home</h2>
                </a>
            </li>
            <li class="icon-box">
                <i class="fa fa-user"></i>
                <a href="{% url 'resume:about' %}">
                    <h2>About</h2>
                </a>
            </li>
            <li class="icon-box">
                <i class="fa fa-briefcase"></i>
                <a href="{% url 'resume:portfolio' %}">
                    <h2>Portfolio</h2>
                </a>
            </li>
            <li class="icon-box active">
                <i class="fa fa-comments"></i>
                <a href="{% url 'blog:blog' %}">
                    <h2>Blog</h2>
                </a>
            </li>
            <li class="icon-box">
                <i class="fa fa-envelope-open"></i>
                <a href="{% url 'resume:contact' %}">
                    <h2>Contact</h2>
                </a>
            </li>
    </ul>
    <!-- Fixed Navigation Ends -->
    <!-- Mobile Menu Starts -->
    <nav role="navigation" class="d-block d-lg-none">
        <div id="menuToggle">
            <input type="checkbox" />
            <span></span>
            <span></span>
            <span></span>
            <ul class="list-unstyled" id="menu">
                <li><a href="{% url 'resume:home' %}"><i class="fa fa-home"></i><span>Home</span></a></li>
                <li><a href="{% url 'resume:about' %}"><i class="fa fa-user"></i><span>About</span></a></li>
                <li><a href="{% url 'resume:portfolio' %}"><i class="fa fa-folder-open"></i><span>Portfolio</span></a></li>
                <li class="active"><a href="{% url 'blog:blog' %}"><i class="fa fa-comments"></i><span>Blog</span></a></li>
                <li><a href="{% url 'resume:contact' %}"><i class="fa fa-envelope-open"></i><span>Contact</span></a></li>
            </ul>
        </div>
    </nav>
    <!-- Mobile Menu Ends -->
</header>
<!-- Header Ends -->
<!-- Page Title Starts -->
<section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1">
    <h1>my <span>blog</span></h1>
    <span class="title-bg">posts</span>
</section>

<div class="container">

    <h2 class="mb-4"> <strong> Viewing posts for {{ cat }} </strong> </h2>
    <hr />

</div>
<!-- Page Title Ends -->
<!-- Main Content Starts -->
<section class="main-content revealator-slideup revealator-once revealator-delay1">
    <div class="container">
        <!-- Articles Starts -->
        <div class="row">
            <!-- Article Starts -->
            {% for post in category_posts %}
                <div class="col-12 col-md-6 col-lg-6 mb-30 " style="flex-wrap: wrap; flex: initial; ">
                    <article class="post-container">
                        <div class="post-thumb">
                            <a href="#" class="card-post__category badge badge-pill badge-primary">{{post.category}}</a>
                            <a href="{% url 'blog:article' post.pk %}" class="d-block position-relative overflow-hidden">
                                <img src="{{post.PreviewImage.url}}" class="img-fluid" alt="Blog Post" style="width: 100%; height:250px; object-fit: cover ">
                            </a>
                        </div>
                        <div class="post-content ">
                            <div class="entry-header">
                                <h3><a href="{% url 'blog:article' post.pk %}">{{post.title}}</a></h3>
                            </div>
                            <div class="entry-content open-sans-font ">
                                <p>{{post.body|slice:':160'|safe}}... <strong> <a href="{% url 'blog:article' post.pk %}">[Readmore]</a> </strong>
                                </p>
                            </div>
                            <hr>

                            <div>
                                ....
                            </div>
                        </div>
                    </article>
                </div>
            {% endfor %}
            <!-- Article Ends -->
            <!-- Article Starts -->
            
            <!-- Pagination Starts 
            <div class="col-12 mt-4">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mb-0">
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                    </ul>
                </nav>
            </div>
             Pagination Ends -->
        </div>
        <!-- Articles Ends -->
    </div>

</section>


        {% endblock content %}

        <!-- Template JS Files -->
        <script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
        <script src="{% static 'js/styleswitcher.js' %}"></script>
        <script src="{% static 'js/preloader.min.js' %}"></script>
        <script src="{% static 'js/fm.revealator.jquery.min.js' %}"></script>
        <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
        <script src="{% static 'js/classie.js' %}"></script>
        <script src="{% static 'js/cbpGridGallery.js' %}"></script>
        <script src="{% static 'js/jquery.hoverdir.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>

    </body>
</html>

blog/templates/blog/footer.html
{% extends 'dashboard-base.html' %}

{% load static %}

{% block content %}


<footer class="footer mt-auto footer-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 small">Copyright &#xA9; Bukhosi Portfolio 2020</div>
            <div class="col-md-6 text-md-right small">
                <a href="#!">Privacy Policy</a>
                &#xB7;
                <a href="#!">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>


{% endblock content %}

blog/templates/blog/update-post.html
{% extends 'dashboard-base.html' %}
{% load static %}

{% block title %}
Update Post
{% endblock title %}

{% block content %} 


    {% if user.is_authenticated %}

        {% include 'blog/navbar.html' %}
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                {% include 'blog/sidebar.html' %}
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
                        <div class="container">
                            <div class="page-header-content pt-4">
                                <div class="row align-items-center justify-content-between">
                                    <div class="col-auto mt-4">
                                        <h1 class="page-header-title">
                                            <div class="page-header-icon"><i data-feather="edit-3"></i></div>
                                            Update blog post
                                        </h1>
                                        <div class="page-header-subtitle">Make changes to your portfolio</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </header>
                    <!-- Main page content-->
                    <div class="container mt-n10">
                        <div class="card mb-4">
                            <div class="card-header">Posts 
                                <a class="btn btn-sm btn-primary ml-2" href="{% url 'blog:add-post' %}">Add New</a>
                                <a class="btn btn-sm btn-primary ml-2" href="{% url 'blog:add-category' %}">Add Category</a>
                            </div>
                            <div class="card-body">
                                <div class="datatable">
                                    <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>Post Title</th>
                                                <th>Author</th>
                                                <th>Category</th>
                                                <th>Date</th>
                                                <th>Status</th>
                                                <th>Actions</th>
                                                
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>Post Title</th>
                                                <th>Author</th>
                                                <th>Category</th>
                                                <th>Date</th>
                                                <th>Status</th>
                                                <th>Actions</th>
                                                
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                        {% for post in object_list %}
                                            <tr>
                                                <td style="font-weight:500;">{{post.title}}</td>
                                                <td>{{post.author.first_name}} {{post.author.last_name}}</td>
                                                <td>{{ post.category }}</td>
                                                <td>{{ post.publish_date }}</td>
                                                <td>
                                                    {% if post.status == "published" %}
                                                        <span class="badge badge-sm badge-info"> <strong> Published </strong> </span>
                                                    {% else %}
                                                        <span class="badge badge-sm badge-warning"> <strong> Draft </strong></span>
                                                    {% endif %}

                                                </td> 
                                                <td>
                                                    <a href="{% url 'blog:edit-post' post.pk %}" class="btn btn-datatable btn-icon btn-transparent-dark mr-2" title="Edit Post"><i style="color: #118ce7;" data-feather="edit"></i></a>
                                                    <a href="{% url 'blog:delete-post' post.pk %}" class="btn btn-datatable btn-icon btn-transparent-dark mr-2" title="Edit Post"><i style="color: red;" data-feather="trash-2"></i></a>
                                                </td>
                                            </tr>
                                        {% endfor %}   
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
                {% include 'blog/footer.html' %}
            </div>
        </div>

    {% else %}

        {% include 'blog/401.html' %}

    {% endif %}



{% endblock content %}